steps:
- name: 'docker/compose:1.19.0'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/cloudbuild-demo-dockercompose']
images: ['gcr.io/$PROJECT_ID/cloudbuild-demo-dockercompose']