steps:
- name: 'docker/compose:latest'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/test2:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/test2:latest',
            '.'
        ]