steps:
- name: 'docker/compose:latest'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_default:latest', 'gcr.io/$PROJECT_ID/cloudbuild-demo-dockercompose']
images: ['gcr.io/$PROJECT_ID/cloudbuild-demo-dockercompose']