steps:
- name: 'docker/compose:1.28.2'
  args: ['up', '-d']
- name: gcr.io/cloud-builders/docker
  id: 'backend'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/cloudbuild-demo-dockercompose:${SHORT_SHA}',
    '-t', 'gcr.io/$PROJECT_ID/cloudbuild-demo-dockercompose:latest'
  ]

